version: "3.9"

services:
  model:
    container_name: openadr_manager
    build:
      context: .
      dockerfile: Manager/Dockerfile
    volumes:
      - ./:/home/OpenADR-manager
      - /var/run/docker.sock:/var/run/docker.sock

    #    tty : true
    environment:
      IS_SERVER: "False"
      TZ: Asia/Seoul
      DB_NICKNAME: server_on_docker

    entrypoint: ["sh", "/home/OpenADR-manager/entrypoint.sh", $GIT_ID, $GIT_PASSWORD]


# local docker 연결시
networks:
  default:
    external: true  # 기존 network와 연결
    name: openadr-docker_default